# This is the distro logos file for catnip.
# Here you can configure all distro logos 
# or add a new one.
#
# https://github.com/iinsertNameHere/catnip

##############################################
##         Distro ASCII-Art Config          ##
##############################################
[none]
margin = [0, 0, 0,]
art = [""]

[catnip]
alias  = "default"
margin = [1, 2, 2,]
art    = [
    "(GN)          ⣀⣀⣠⣠⣶⠦⢴⣦⣀⣠⣀  ",
    "(GN)     ⢀⣤⣴⠿⠋⠿⠋⠁   ⠉⠉⠉⠉⣿⡇ ",
    "(GN)    ⣴⡟⠙⠁   ⡆        ⣰⡿ ",
    "(GN)  ⣰⡿⡟   ⡇ ⢸⣧⣚⡀     ⢻⡇  ",
    "(GN) ⢠⣿⠁ ⢸  ⣇⡴⠋⠉⠉     ⣰⡿⠁  ",
    "(GN) ⢸⣏  ⢸⣀⣴⠟⠛⠛⠉⠁    ⢚⣿    ",
    "(GN) ⠸⣿  ⣼⣿⠧⠤⠤⠔   ⣀⣤⡾⠛⠁    ",
    "(GN)  ⠹⣧⣾⡟⠁     ⢀⣠⣼⡿       ",
    "(GN)  ⢀⣼⠟⣼⡟⠻⠿⠛⠛⠛⠉⠁         ",
    "(GN)  ⠘⠿⠾⠏                 ",
]

[tux]
margin = [2, 2, 3,]
art    = [
    "(BK)      .--.     ",
    "(BK)     |!DT!o(BK)_!DT!o (BK)|    ",
    "(BK)     |(YW):_/ (BK)|    ",
    "(BK)    /!DT!/   \\ (BK)\\   ",
    "(BK)   (!DT!|     | (BK))  ",
    "(YW)  /'!DT!|_   _/(YW)'\\  ",
    "(YW)  \\___)(BK)=(YW)(___/  ",
]

[arch]
margin = [2, 2, 3,]
art    = [
    "{BE}      /\\      ",
    "{BE}     /  \\     ",
    "{BE}    /\\   \\    ",
    "{BE}   /      \\   ",
    "{BE}  /   ,,   \\  ",
    "{BE} /   |  |  -\\ ",
    "{BE}/_-''    ''-_\\",
]

[archcraft]
margin = [2, 2, 3,]
art    = [
    "{GN}      .      ",
    "{GN}     / \\     ",
    "{GN}    /\\  \\    ",
    "{GN}   /     \\   ",
    "{GN}  / , ^ , \\  ",
    "{GN} /  <   > -\\ ",
    "{GN}/_-''   ''-_\\",
]

[artix]
margin = [2,2,2,]
art    = [
    "{BE}      /\\      ",
    "{BE}     /  \\     ",
    "{BE}    /`'.,\\    ",
    "{BE}   /     ',   ",
    "{BE}  /      ,`\\  ",
    "{BE} /   ,.'`.  \\ ",
    "{BE}/.,'`     `'.\\",
]

[windows]
margin = [2, 2, 4,]
art    = [
    "[RD]       [GN]       ",
    "[RD]       [GN]       ",
    "[RD]       [GN]       ",
    "[BE]       [YW]       ",
    "[BE]       [YW]       ",
    "[BE]       [YW]       ",
]

[ubuntu]
margin = [0, 2, 4,]
art    = [
    "{RD}                .-.   ",
    "{RD}        .-'````(   )  ",
    "{RD}     ,`\\ \\    `-`.    ",
    "{RD}    /   \\ '````-.   ` ",
    "{RD}  .-.  ,         `___:",
    "{RD} (   ) :          ___ ",
    "{RD}  `-`  `         ,   :",
    "{RD}    \\   / ,....-`   , ",
    "{RD}     `./ /      .-.`  ",
    "{RD}        `-....-(   )  ",
    "{RD}                `-`   ",
]

[manjaro]
margin = [2, 2, 4,]
art    = [
    "<GN>        !DT!  <GN>    ",
    "<GN>        !DT!  <GN>    ",
    "<GN>   !DT!       <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
    "<GN>   !DT!  <GN>   !DT!  <GN>    ",
]

[debian]
margin = [1, 2, 3,]
art    = [
    "(RD)  , - = - ,   ",
    "(RD) =    ,,   =  ",
    "(RD)=   :°   ;  = ",
    "(RD)=   :.      = ",
    "(RD)^=    ° == °  ",
    "(RD)°=.           ",
    "(RD) ^==..        ",
    "(RD)   ^^°==..    ",
    "(RD)        ^^°=  ",
]

[nixos]
margin = [1, 2, 3,]
art    = [
    "{BE}     ⣀⡀  {CN}⣀⣀⡀ ⢀⣀     ",
    "{BE}    ⠈⢿⣷⡀ {CN}⠈⢿⣷⣄⣾⡿⠃    ",
    "{BE}  ⢀⣶⣶⣾⣿⣿⣶⣶⣮{CN}⣻⣿⣿⠁ {BE}⢠⡀  ",
    "{CN}     ⣩⣭⡍    ⢻⣿⣆{BE}⢠⣿⡗  ",
    "{CN}⢠⣤⣤⣤⣴⣿⠟      ⠹{BE}⣳⣿⣿⣤⣤⡄",
    "{CN}⠘⠛⠛⣿⣿⢯{BE}⣦      ⣰⣿⠟⠛⠛⠛⠃",
    "{CN}  ⢼⣿⠋{BE}⠹⣿⣧{CN}⢀⣀⣀⣀⣜⣛⣋⣀⣀⡀  ",
    "{CN}  ⠈⠃ {BE}⢀⣾⣿⣷{CN}⡻⠿⠿⢿⣿⡿⠿⠿⠁  ",
    "{BE}    ⢠⣾⡿⠙⢿⣷⡀ {CN}⠈⢿⣷⡄    ",
    "{BE}     ⠉⠁ ⠈⠉⠉  {CN}⠈⠉     ",
]

[fedora]
margin = [1, 2, 3,]
art    = [
    "(WE)       _____  ",
    "(WE)     /   __)(BE)\\ ",
    "(WE)     |  /  (BE)\\ \\",
    "(BE)  __(WE)_|  |_(BE)_/ /",
    "(BE) / (WE)(_    _)(BE)_/ ",
    "(BE)/ /  (WE)|  |     ",
    "(BE)\\ \\(WE)__/  |     ",
    "(BE) \\(WE)(_____/     ",

]

[void]
margin = [2, 2, 4,]
art    = [
    "(GN)    _______  ",
    "(GN) _ \\______ - ",
    "(GN)| \\  ___  \\ |",
    "(GN)| | /   \\ | |",
    "(GN)| | \\___/ | |",
    "(GN)| \\______ \\_|",
    "(GN) -_______\\   ",
]

[mint]
alias = "linuxmint"
margin = [2, 2, 4,]
art    = [
    "{CN} ___________ ",
    "{CN}|_          \\",
    "{CN}  | (WE)| _____ {CN}|",
    "{CN}  | (WE)| | | | {CN}|",
    "{CN}  | (WE)| | | | {CN}|",
    "{CN}  | (WE)\\_____/ {CN}|",
    "{CN}  \\_________/",
]

[raspbian]
alias = "raspberrypios"
margin = [2, 2, 3,]
art    = [
    "{GN}  __  __   ",
    "{GN} (_\\)(/_)  ",
    "{RD} (_(__)_)  ",
    "{RD}(_(_)(_)_) ",
    "{RD} (_(__)_)  ",
    "{RD}   (__)    ",
]

[android]
margin = [2, 2, 2,]
art    = [
    "{GN}  ;,           ,;  ",
    "{GN}   ';,.-----.,;'   ",
    "{GN}  ,'           ',  ",
    "{GN} /    O     O    \\ ",
    "{GN}|                 |",
    "{GN}'-----------------'",
]

[gentoo]
margin = [2, 2, 3,]
art    = [
    "{MA} _-----_   ",
    "{MA}(       \\  ",
    "{MA}\\    0   \\ ",
    "{WE} \\        )",
    "{WE} /      _/ ",
    "{WE}(     _-   ",
    "{WE}\\____-     ",
]

[endeavour]
alias = "endeavouros"
margin = [2, 2, 3,]
art    = [
    "{MA}       /\\     ",
    "{RD}     /{MA}/  \\{CN}\\   ",
    "{RD}    /{MA}/    \\{CN}\\  ",
    "{RD}  / {MA}/     _) {CN})",
    "{RD} /_{MA}/___-- {CN}__- ",
    "{CN}/____--       ",
]

[pop]
alias = "popos, pop_os"
margin = [1, 1, 2,]
art    = [
    "{CN}  ______             ",
    "{CN}  \\   _ \\        __  ",
    "{CN}   \\ \\ \\ \\      / /  ",
    "{CN}    \\ \\_\\ \\    / /   ",
    "{CN}     \\  ___\\  /_/    ",
    "{CN}      \\ \\    _       ",
    "{CN}     __\\_\\__(_)_     ",
    "{CN}    (___________)    ",
]